//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musica
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANCION
    {
        public string CAN_ID { get; set; }
        public string ALB_ID { get; set; }
        public string GEN_ID { get; set; }
        public string CAN_NOMBRE { get; set; }
        public Nullable<decimal> CAN_DURACION { get; set; }
    }
}
